EnglishWeb/urls.py
from django.contrib import admin
from django.urls import path
from home_page import views
from django.urls import re_path as url
from django.urls import include

urlpatterns = [
    url(r'^', include('home_page.urls')),
    url(r'^first_app/', include('first_app.urls')),
    url(r'^demoform/', include('demoform.urls')),
    url(r'^download_youtube/', include('download_youtube.urls')),
    url(r'^restapi/', include('rest_api.urls')),
    url(r'^new_polls/', include('new_polls.urls')),
    url(r'^chatbot/', include('chatbot.urls')),
    path('admin/', admin.site.urls),
]

chatbot/urls.py
from django.urls import re_path, path
from .views import request_answer_view

urlpatterns = [
    # re_path('^', UserListCreate.as_view(), name='chatbot'),
    path('chatbot_api/', request_answer_view, name='chatbot-api'),
    # path('users/', UserListCreate.as_view(), name='user-list'),
    # path('users/<int:pk>/', UserDetail.as_view(), name='user-detail'),
]

download_youtube/urls.py
from django.urls import re_path as url
from download_youtube import views

app_name = 'download_youtube'


urlpatterns = [
    url(r'^$', views.YoutubeDownloader.as_view(), name='dashboard'),
    # url(r'^form', views.YoutubeDownloader.youtube_form(), name='youtube_form'),
    url(r'^create', views.YoutubeDownloader.as_view(), name='create'),
    url(r'^detail/(?P<pk>\d+)', views.YoutubeDetail.as_view(), name='detail'),
    url(r'^detail/(?P<pk>\d+)/update', views.YoutubeUpdate.as_view(), name='update'),
    url(r'^detail/(?P<pk>\d+)/delete', views.YoutubeDelete.as_view(), name='delete'),
]

download_youtube/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View, generic

from first_app.models import Hall


# Create your views here.

# CRUD
class YoutubeDownloader(generic.CreateView):
    model = Hall
    fields = ['title']
    template_name = 'download_youtube/create.html'
    success_url = reverse_lazy('download_youtube:youtube_downloader')

    def form_valid(self, form):
        form.instance.user = self.request.user
        super(YoutubeDownloader, self).form_valid(form)
        return redirect('download_youtube:youtube_downloader')


class YoutubeDetail(generic.DetailView):
    model = Hall

    template_name = 'download_youtube/detail.html'


class YoutubeUpdate(generic.UpdateView):
    model = Hall
    template_name = 'youtube_download/update.html'
    fields = ['title']
    success_url = reverse_lazy('download_youtube:dashboard')


class YoutubeDelete(generic.DeleteView):
    model = Hall
    template_name = 'youtube_download/delete.html'
    fields = 'title'
    success_url = reverse_lazy('download_youtube:dashboard')

EnglishWeb/templates/download_youtube/create.html
{% extends 'download_youtube/index.html' %}
{% block title %}
Create youtube
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Create</button>
</form>
{% endblock %}

EnglishWeb/templates/download_youtube/dashboard.html
{% extends 'download_youtube/index.html' %}
{% block title %}
Dashboard
{% endblock %}
{% block content %}

{% endblock %}

EnglishWeb/templates/download_youtube/delete.html
{% extends 'download_youtube/index.html' %}
{% block title %}
Delete youtube
{% endblock %}
{% block content %}
<h2>Are you sure you want to delete this Hall</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Delete</button>
</form>

<br>
<h2><a href="{% url 'download_youtube:detail' hall.id %}">{{ hall.title }}</a></h2>
{% endblock %}

EnglishWeb/templates/download_youtube/detail.html
{% extends 'download_youtube/index.html' %}
{% block title %}
Detail
{% endblock %}
{% block content %}
<h1>{{ hall.title }}</h1>
<h4 class="text-muted">{{ hall.user.username }}</h4>

{% endblock %}

EnglishWeb/templates/download_youtube/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load static %}
{% block title %}
Trang chủ
{% endblock %}
{% block menu %}
<li class=" home-page-li"><a class="active" href="{% url 'download_youtube:dashboard' %}">Dash board</a></li>
<li class=" home-page-li"><a href="#">Detail</a></li>
<li class=" home-page-li"><a href="#item3">Item 3</a></li>
<li class=" home-page-li"><a href="#item4">Item 4</a></li>
{% endblock %}
{% block content %}
{% endblock %}

EnglishWeb/templates/download_youtube/update.html
{% extends 'download_youtube/index.html' %}
{% block title %}
Update youtube
{% endblock %}
{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}