EnglishWeb/urls.py
from django.contrib import admin
from django.urls import path
from home_page import views
from django.urls import re_path as url
from django.urls import include

urlpatterns = [
    url(r'^', include('home_page.urls')),
    url(r'^first_app/', include('first_app.urls')),
    url(r'^demoform/', include('demoform.urls')),
    url(r'^download_youtube/', include('download_youtube.urls')),
    url(r'^restapi/', include('rest_api.urls')),
    url(r'^new_polls/', include('new_polls.urls')),
    url(r'^chatbot/', include('chatbot.urls')),
    path('admin/', admin.site.urls),
]

chatbot/urls.py
from django.urls import re_path, path
from .views import request_answer_view

urlpatterns = [
    # re_path('^', UserListCreate.as_view(), name='chatbot'),
    path('chatbot_api/', request_answer_view, name='chatbot-api'),
    # path('users/', UserListCreate.as_view(), name='user-list'),
    # path('users/<int:pk>/', UserDetail.as_view(), name='user-detail'),
]

download_youtube/urls.py
from django.urls import re_path as url
from download_youtube import views

app_name = 'download_youtube'


urlpatterns = [
    url(r'^$', views.YoutubeDownloader.as_view(), name='dashboard'),
    # url(r'^form', views.YoutubeDownloader.youtube_form(), name='youtube_form'),
    url(r'^create', views.YoutubeDownloader.as_view(), name='create'),
    url(r'^detail/(?P<pk>\d+)', views.YoutubeDetail.as_view(), name='detail'),
    url(r'^detail/(?P<pk>\d+)/update', views.YoutubeUpdate.as_view(), name='update'),
    url(r'^detail/(?P<pk>\d+)/delete', views.YoutubeDelete.as_view(), name='delete'),
]

first_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import re_path as url
from first_app import views
from django.contrib.auth import views as auth_views


app_name = 'first_app'


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url('admin/', admin.site.urls),
    # AUTH
    url('signup', views.SignUp.as_view(), name='signup'),
    url('login', auth_views.LoginView.as_view(), name='login'),
    url('logout', auth_views.LogoutView.as_view(), name='logout'),
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

home_page/urls.py
from django.urls import re_path as url
from home_page import views

app_name = 'homepage'

urlpatterns = [
    url(r'^$', views.index, name='home'),
]

EnglishWeb/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/base_style.css' %}" />
</head>
<body>
    <div class="base-container">
        <div class="base-header">
            <div class="base-logo">
                <h1>This is img</h1>
            </div>
            <div>
                <ul class="base-ul">
                    <li class="base-li"><a class="active" href="{% url 'homepage:home' %}">Home</a> </li>
                    <li class="base-li"><a href="#gameguides">Game guides</a> </li>
                    <li class="base-li"><a href="{% url 'first_app:index' %}">Example</a> </li>
                    <li class="base-li"><a href="{% url 'download_youtube:dashboard' %}">Youtube Download</a></li>
                </ul>
            </div>
        </div>
        <div class="container">
            <link rel="stylesheet" href="{% static 'css/homepage_index.css' %}"/>
            <div class="home-page-container">
                <div class="home-page-menu">
                    <ul class="home-page-ul">
                        {% block menu %}
                        {% endblock %}
                    </ul>
                </div>
                <div class="home-page-content-container">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>


</body>
</html>