EnglishWeb/urls.py
from django.contrib import admin
from django.urls import path
from home_page import views
from django.urls import re_path as url
from django.urls import include

urlpatterns = [
    url(r'^', include('home_page.urls')),
    url(r'^first_app/', include('first_app.urls')),
    url(r'^demoform/', include('demoform.urls')),
    url(r'^download_youtube/', include('download_youtube.urls')),
    url(r'^restapi/', include('rest_api.urls')),
    url(r'^new_polls/', include('new_polls.urls')),
    url(r'^chatbot/', include('chatbot.urls')),
    path('admin/', admin.site.urls),
]

chatbot/urls.py
from django.urls import re_path, path
from .views import request_answer_view

urlpatterns = [
    # re_path('^', UserListCreate.as_view(), name='chatbot'),
    path('chatbot_api/', request_answer_view, name='chatbot-api'),
    # path('users/', UserListCreate.as_view(), name='user-list'),
    # path('users/<int:pk>/', UserDetail.as_view(), name='user-detail'),
]

new_polls/urls.py
from django.urls import re_path as url

from . import views

app_name = 'new_polls'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

new_polls/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.


class Question(models.Model):

    quest_text = models.CharField(max_length=200)
    pub_data = models.DateTimeField('date_published')

    def __str__(self):
        return self.quest_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_data <= now

    was_published_recently.admin_order_field = 'pub_data'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

new_polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'new_polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_data__lte=timezone.now()).order_by('-pub_data')[:5]



class DetailView(generic.DetailView):
    model = Question
    template_name = 'new_polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """

        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'new_polls/result.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
    # Redisplay the question voting form.
        return render(request, 'new_polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('new_polls:results', args=(question.id,)))

EnglishWeb/templates/new_polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'new_polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

EnglishWeb/templates/new_polls/index.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/new_polls/style.css' %}" />
{% if latest_question_list %}
<ul>
{% for question in latest_question_list %}
<li><a href="{% url 'new_polls:detail' question.id %}">{{ question.quest_text }}</a></li>
{% endfor %}
</ul>
{% else %}
<p>No polls are available.</p>
{% endif %}

EnglishWeb/templates/new_polls/result.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'new_polls:detail' question.id %}">Vote again?</a>